website/blog/urls.py
# coding=utf-8
from django.conf.urls import url
from .views import *


urlpatterns = [
    url(r'^$', index, name='index'),
]

website/website/urls.py
# coding=utf-8
"""
website URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^u/', include('users.urls', namespace='users', app_name='users')),
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
    url(r'^', include('Questionnaire.urls', namespace="question", app_name="question")),
]
if settings.DEBUG:
    from django.contrib import admin
    import debug_toolbar
    urlpatterns.insert(0, url(r'^admin/', admin.site.urls))
    urlpatterns.insert(0, url(r'^debug/', include(debug_toolbar.urls)))

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/blog/views.py
from django.shortcuts import render


def index(request):
    return render('blog/index.html')

website/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}
    {% endblock %}</title>

    {% load staticfiles %}
    <!-- Load the jQuery library -->
    <script src="{% static 'Questionnaire/js/vendor/jquery.js' %}"></script>

    <!-- Load the bootstrap file's -->
    <!-- <link rel="stylesheet" href="{% static 'Questionnaire/bootstrap.min.css' %}"> -->
    <link rel="stylesheet" href="{% static 'Questionnaire/flatly.min.css' %}">
    <script src="{% static 'Questionnaire/bootstrap.min.js' %}"></script>

    <!-- Load the app specific stuff -->
    <link rel="stylesheet" href="{% static 'Questionnaire/app.css' %}">
    <script src="{% static 'Questionnaire/app.js' %}"></script>

    <!-- The Google fonts links -->
    <link href="https://fonts.googleapis.com/css?family=Lemonada" rel="stylesheet">

</head>
<body>
    <!-- Start Top Bar -->
    <nav class="navbar navbar-default">
        <div class="container-fluid">
        <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand lemonada" href="{% url 'blog:index' %}">Blog</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
        <li class="active"><a href="{% url 'blog:create_post' %}">Create a Post<span class="sr-only">(current)</span></a></li>
        <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">More Actions <span class="caret"></span></a>
            <ul class="dropdown-menu dropdown-menu-right" role="menu">
                <li><a href="{% url 'question:index' %}">Visit Questionn</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li><a href="#">Separated link</a></li>
                <li class="divider"></li>
                <li><a href="#">One more separated link</a></li>
            </ul>
        </li>
    </ul>
    <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
            <input class="form-control" placeholder="Search" type="text">
        </div>
        <button type="submit" class="btn btn-success">Submit</button>
    </form>
    </div>
    </div>
    </nav>
    <!-- End Top Bar -->
    {% block body %}{% endblock %}

    <script>
      $(document).foundation();
    </script>
</body>
</html>

website/templates/blog/index.html
{% extends 'base.html' %}

{% block title %}
Questionn
{% endblock %}

{% block body %}

<center><h1 class='lemonada'>The Blogg is abandoned in favour of Rlog which be coming online 
very soon. See you there!!</h1></center>

{% endblock %}