website/Questionnaire/urls.py
# coding=utf-8
from django.conf.urls import url
from .views import CreateViews, DeleteViews, UpdateViews, MiscViews

app_name = 'question'

urlpatterns = [
    url(r'^$', MiscViews.QuestionIndexView.as_view(), name="index"),
    url(r'^add/$', CreateViews.QuestionCreateView.as_view(), name='add'),
    url(r'^question/(?P<slug>[-\w]+)/$', MiscViews.QuestionDetailView.as_view(), name='details'),
    url(r'^answer/(?P<slug>[-\w]+)/$', CreateViews.AnswerCreateView.as_view(), name='answer'),
    url(r'^comment/(?P<question_slug>[-\w]+)/(?P<pk>[0-9]+)/(?P<refer_model>[\w]+)/$',
        CreateViews.CommentCreateView.as_view(), name='comment'),

    url(r'^answer(?P<slug>[-\w]+)/(?P<pk>[0-9]+)/delete/$',
        DeleteViews.AnswerDeleteView.as_view(), name='answer_delete'),

    url(r'^comment/(?P<pk>[0-9]+)/(?P<slug>[-\w]+)/delete',
        DeleteViews.CommentDeleteView.as_view(), name='delete_comment'),

    url(r'^question/(?P<slug>[-\w]+)/delete/$', DeleteViews.QuestionDeleteView.as_view(), name='delete_question'),
    url(r'^question/(?P<slug>[-\w]+)/edit/$', UpdateViews.QuestionUpdateView.as_view(), name='edit_question'),

    # url(r'like/(?P<slug>[-\w]+)/(?P<pk>[-0-9]+)/(?P<refer_model>[-\w]+)/(?P<like>[\w]+)/',
    #    CreateViews.LikeCreateView.as_view(), name='like'),
]

website/blog/urls.py
# coding=utf-8
from django.conf.urls import url
from .views import *


urlpatterns = [
    url(r'^$', index, name='index'),
]

website/users/urls.py
# coding=utf-8
from django.conf.urls import url
from .views import UserLoginView, logout_user, UserDetailView, UserRegisterView

urlpatterns = [
    url(r'^login/$', UserLoginView.as_view(), name='login_user'),
    url(r'^logout/$', logout_user, name='logout_user'),
    url(r'^register/$', UserRegisterView.as_view(), name='register_user'),
    url(r'^(?P<username>[-\w]+)/$', UserDetailView.as_view(), name='user_details'),
]

website/website/urls.py
# coding=utf-8
"""
website URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^u/', include('users.urls', namespace='users', app_name='users')),
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
    url(r'^', include('Questionnaire.urls', namespace="question", app_name="question")),
]
if settings.DEBUG:
    from django.contrib import admin
    import debug_toolbar
    urlpatterns.insert(0, url(r'^admin/', admin.site.urls))
    urlpatterns.insert(0, url(r'^debug/', include(debug_toolbar.urls)))

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/Questionnaire/models.py
# coding=utf-8
from .helpers import generate_random_id
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse
from django.utils import timezone

class Question(models.Model):
    title = models.CharField(max_length=250)
    body = models.TextField()
    asked_by = models.ForeignKey("users.UserModel")
    pub_date = models.DateTimeField(auto_now_add=timezone.now)
    slug = models.SlugField(max_length=350, unique=True)
    up_votes = models.PositiveIntegerField(default=0)
    down_votes = models.PositiveIntegerField(default=0)

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        # super(Question, self).save(force_insert, force_update, using, update_fields)
        if not self.slug:
            self.slug = slugify(self.title)+"-"+generate_random_id()
        super(Question, self).save(force_insert, force_update, using, update_fields)

    def get_absolute_url(self):
        return reverse('question:details', kwargs={'slug': self.slug})

    def __str__(self):
        return self.title


class Answer(models.Model):
    answer = models.TextField()
    question = models.ForeignKey(Question, models.CASCADE)
    published_date = models.DateTimeField(auto_now_add=timezone.now)
    last_edited = models.DateTimeField(auto_now=timezone.now)
    answered_by = models.ForeignKey('users.UserModel', models.CASCADE)
    draft = models.BooleanField(default=False)
    up_votes = models.PositiveIntegerField(default=0)
    down_votes = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.question.title+"===>"+self.answer[:31]


class Comment(models.Model):
    question_relation = models.ForeignKey(Question, models.CASCADE, blank=True, null=True)
    answer_relation = models.ForeignKey(Answer, models.CASCADE, blank=True, null=True)
    body = models.CharField(max_length=300)
    pub_date = models.DateTimeField(auto_now_add=True)
    comment_by = models.ForeignKey('users.UserModel', models.CASCADE)
    up_votes = models.PositiveIntegerField(default=0)
    down_votes = models.PositiveIntegerField(default=0)

    def __str__(self):
        return "{0} by {1} at {2}".format(self.body, self.comment_by, self.pub_date)

website/Questionnaire/forms.py
# coding=utf-8
from django import forms
from . import models
from pagedown.widgets import PagedownWidget


class QuestionForm(forms.ModelForm):
    title = forms.CharField(max_length=250, label='Enter title for the Question')
    body = forms.CharField(widget=PagedownWidget(), label='Enter the questions details')

    class Meta:
        model = models.Question
        exclude = ('asked_by', 'slug', 'pub_date', 'up_votes', 'down_votes')


class AnswerForm(forms.ModelForm):
    draft = forms.BooleanField(label='Save as draft', required=False, initial=False)
    answer = forms.CharField(widget=PagedownWidget())

    class Meta:
        model = models.Answer
        exclude = ('question', 'published_date', 'answered_by', 'up_votes', 'down_votes')


class CommentsForm(forms.ModelForm):
    class Meta:
        model = models.Comment
        exclude = ('question_relation', 'answer_relation', 'pub_date', 'comment_by', 'up_votes', 'down_votes')

website/Questionnaire/views/CreateViews.py
# coding=utf-8
from .. import models, forms
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import CreateView


class QuestionCreateView(CreateView):
    model = models.Question
    form_class = forms.QuestionForm
    template_name = 'Questionnaire/form.html'
    success_url = 'question:details'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated() == False:
            return redirect('users:login_user')
        return super(QuestionCreateView, self).get(request, args, kwargs)

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            model = form.save(commit=False)
            model.asked_by = request.user
            model.save()
            return redirect(self.success_url, slug=model.slug)


class AnswerCreateView(CreateView):
    model = models.Answer
    form_class = forms.AnswerForm
    template_name = 'Questionnaire/form.html'
    success_url = 'question:details'

    def post(self, request, *args, **kwargs):
        question = get_object_or_404(models.Question, slug=kwargs['slug'])
        form = self.form_class(request.POST)
        if form.is_valid():
            model = form.save(commit=False)
            model.question = question
            model.answered_by = request.user
            model.save()
            return redirect(self.success_url, slug=kwargs.get('slug'))


class CommentCreateView(CreateView):
    model = models.Comment
    form_class = forms.CommentsForm
    template_name = 'Questionnaire/form.html'
    success_url = 'question:details'

    def post(self, request, *args, **kwargs):
        reference_model = kwargs['refer_model']
        question_model, answer_model = None, None
        if reference_model == 'question':
            question_model = get_object_or_404(models.Question, pk=kwargs['pk'])
        else:
            answer_model = get_object_or_404(models.Answer, pk=kwargs['pk'])
        form = self.form_class(request.POST)
        if form.is_valid():
            model = form.save(commit=False)
            model.question_relation, model.answer_relation = question_model, answer_model
            model.comment_by = request.user
            model.save()
            return redirect(self.success_url, slug=kwargs['question_slug'])

website/Questionnaire/views/DeleteViews.py
# coding=utf-8
from django.views.generic import DeleteView
from django.shortcuts import get_object_or_404, redirect
from .. import models


class QuestionDeleteView(DeleteView):
    model = models.Question
    success_url = 'question:index'
    template_name = 'Questionnaire/question_confirm_delete.html'

    def post(self, request, *args, **kwargs):
        question = get_object_or_404(self.model, slug=kwargs['slug'])
        if question.asked_by == request.user:
            question.delete(keep_parents=False)
            return redirect(self.success_url)
        else:
            return redirect('question:details', slug=kwargs['slug'])


class AnswerDeleteView(DeleteView):
    model = models.Answer
    success_url = 'question:details'
    template_name = 'Questionnaire/answer_confirm_delete.html'

    def post(self, request, *args, **kwargs):
        question = get_object_or_404(models.Question, slug=kwargs['slug'])
        answer = get_object_or_404(question.answer_set, pk=kwargs['pk'])
        if request.user == answer.answered_by:
            answer.delete(keep_parents=True)
        return redirect('question:details', slug=kwargs['slug'])


class CommentDeleteView(DeleteView):
    model = models.Comment
    success_url = 'question:details'

    def get(self, request, *args, **kwargs):
        comment = get_object_or_404(self.model, pk=kwargs['pk'])
        if request.user == comment.user:
            comment.delete(keep_parents=True)
        return redirect(self.success_url, slug=kwargs['slug'])

website/Questionnaire/views/MiscViews.py
# coding=utf-8
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import get_object_or_404, render
from Questionnaire import models
from django.views.generic import ListView, DetailView


class QuestionIndexView(ListView):
    model = models.Question
    context_object_name = 'questions'
    template_name = 'Questionnaire/index.html'
    ordering = '-pub_date'

    def get(self, request, *args, **kwargs):
        pages = Paginator(self.get_queryset(), 10)
        page = request.GET.get('page')

        try:
            questions = pages.page(page)
        except PageNotAnInteger:
            questions = pages.page(1)
        except EmptyPage:
            questions = pages.page(pages.num_pages)

        return render(request, self.template_name, {self.context_object_name: questions})


class QuestionDetailView(DetailView):
    model = models.Question
    context_object_name = 'question'
    template_name = 'Questionnaire/question_details.html'

    def get(self, request, *args, **kwargs):
        question = get_object_or_404(self.model, slug=kwargs['slug'])
        answers = question.answer_set.order_by('-published_date')
        return render(request, self.template_name, {self.context_object_name: question, 'answers': answers})

website/Questionnaire/views/UpdateViews.py
# coding=utf-8
from django.views.generic import UpdateView
from Questionnaire import models, forms
from django.urls import reverse


class QuestionUpdateView(UpdateView):
    model = models.Question
    form_class = forms.QuestionForm
    template_name = 'Questionnaire/form.html'

    def get_success_url(self):
        target_slug = self.object.slug
        return reverse('question:details', kwargs={'slug': target_slug})

website/templates/Questionnaire/answer_confirm_delete.html
{% extends 'Questionnaire/base.html' %}

{% block title %}
    Delete {{ object.title }}
{% endblock %}


{% block body %}
    <h1>Delete {{ object.title }} ?</h1>
    <form method="post">
        {% csrf_token %}
        <div>

            <button type="submit" class="btn btn-danger">Yes</button>
            &nbsp;&nbsp;&nbsp;
            <a href="{% url 'question:details' object.question.slug %}" class="btn btn-success">No</a>
        </div>
    </form>
{% endblock %}

website/templates/Questionnaire/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}
    {% endblock %}</title>

    {% load staticfiles %}
    <!-- Load the jQuery library -->
    <script src="{% static 'Questionnaire/js/vendor/jquery.js' %}"></script>

    <!-- Load the bootstrap file's -->
    <!-- <link rel="stylesheet" href="{% static 'Questionnaire/bootstrap.min.css' %}"> -->
    <link rel="stylesheet" href="{% static 'Questionnaire/flatly.min.css' %}">
    <script src="{% static 'Questionnaire/bootstrap.min.js' %}"></script>

    <!-- Load the app specific stuff -->
    <link rel="stylesheet" href="{% static 'Questionnaire/app.css' %}">
    <script src="{% static 'Questionnaire/app.js' %}"></script>

    <!-- The Google fonts links -->
    <link href="https://fonts.googleapis.com/css?family=Lemonada" rel="stylesheet">

</head>
<body>
    <!-- Start Top Bar -->
    <nav class="navbar navbar-default">
        <div class="container-fluid">
        <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand lemonada" href="{% url 'question:index' %}">Questionn</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
        <li class="active"><a href="{% url 'question:add' %}">Ask Question<span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
            <ul class="dropdown-menu dropdown-menu-right" role="menu">
                <li><a href="{% url 'blog:index' %}">Visit the Blogg</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li><a href="#">Separated link</a></li>
                <li class="divider"></li>
                <li><a href="{% url 'users:login_user' %}">Login</a></li>
            </ul>
        </li>
    </ul>
    <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
            <input class="form-control" placeholder="Search" type="text">
        </div>
        <button type="submit" class="btn btn-success">Submit</button>
    </form>
    </div>
    </div>
    </nav>
    <!-- End Top Bar -->
    {% block body %}{% endblock %}

    <script>
      $(document).foundation();
    </script>
</body>
</html>

website/templates/Questionnaire/form.html
{% extends 'Questionnaire/base.html' %}

{% block title %}
    Post your Question - Questionarre
{% endblock %}

{% block body %}
    {% load crispy_forms_tags %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
                <button class="btn btn-success" type="submit" value="Submit">Submit</button>
        {% crispy form %}
    </form>
{% endblock %}

website/templates/Questionnaire/index.html
{% extends 'Questionnaire/base.html' %}

{% block title %}
    Questionn | Welcome
{% endblock %}

{% block body %}
    {% load humanize %}

    {% for question in questions %}
    <div>
      <div class="center-block">
        <h3 class="sub-header">
        <a href="{% url 'question:details' question.slug %}">{{ question.title }}</a>
        <small>{{ question.pub_date | time | naturaltime }}</small>&nbsp;<small>{{ question.pub_date | date | naturalday }}</small></h3>
        {% load markdown_deux_tags %}
        <p>{{ question.body | markdown | truncatewords:40 | linebreaks}}</p>
        <div>
          <ul>
            <li>Author: {{ question.asked_by }}</li>
            <li>Up Votes: {{ question.up_votes }}</li>
            <li>Down Votes: {{ question.down_votes }}</li>
            <li class="fa-comments-o">Answers: {{ question.answer_set.count }}</li>
            <li class="fa-comments-o">Comments: {{ question.comment_set.count }}</li>
          </ul>
        </div>
      </div>
    </div>
    {% endfor %}

<center><div class="pagination">
    <ul class="pager">
    {% if questions.has_previous %}
        <li class="previous active"><a href="?page={{ questions.previous_page_number }}">&larr; Newer</a></li>
    {% else %}
        <li class="previous inactive"><a href="#">&larr; Newer</a></li>
    {% endif %}
    &nbsp;&nbsp;
    {% if questions.has_next %}
        <li class="next active"><a href="?page={{ questions.next_page_number }}">Older &rarr;</a></li>
    {% else %}
        <li class="next inactive"><a href="#">Older &rarr;</a></li>
    {% endif %}
    </ul>
</div></center>

{% endblock %}

website/templates/Questionnaire/question_confirm_delete.html
{% extends 'Questionnaire/base.html' %}

{% block title %}
    Delete {{ object.title }}
{% endblock %}


{% block body %}
    <h1>Delete {{ object.title }} ?</h1>
    <form method="post">
        {% csrf_token %}
        <div>

            <button type="submit" class="btn btn-danger">Yes</button>
            &nbsp;&nbsp;&nbsp;
            <a href="{% url 'question:details' object.slug %}" class="btn btn-success">No</a>
        </div>
    </form>
{% endblock %}

website/templates/Questionnaire/question_details.html
{% extends 'Questionnaire/base.html' %}

{% block title %}
{{ question.title }} - Questionnaire
{% endblock %}

{% block body %}
    {% load markdown_deux_tags %}
    <br><br>
    <div class="jumbotron">
    <h1 class="title-bar-title center-block text-center">{{ question.title }}</h1><br>
    <em>Asked by {{ question.asked_by }} at {{ question.pub_date }}</em>
    <br><br>
    {{ question.body | markdown | linebreaks }}
        <div class="glyphicon glyphicon-hand-up"></div>Up Votes: {{ question.up_votes }}<br>
    Down Votes: {{ question.down_votes }}<br>
    <a class="small btn btn-danger" href="{% url 'question:delete_question' question.slug%}">Delete</a>
    <a class="small edit-shortcut" href="{% url 'question:edit_question' question.slug %}">Edit Question</a>
    </div>

    <hr class="form-horizontal">
        {% for comment in question.comment_set.all %}
            {{ comment.body }} - {{ comment.user_name }} at {{ comment.pub_date }}&nbsp;
            <a class="small" href="{% url 'question:delete_comment' comment.pk question.slug %}">Delete</a>
            <hr class="form-horizontal">
        {% endfor %}
    <br>
    <a style="color: #5e5e5e" href="{% url 'question:comment' question.slug question.pk 'question' %}">Add a Comment</a>

    <br><br><br>
    {% load markdown_deux_tags %}
    {% for answer in answers %}
        {{ answer.answer | markdown | linebreaks }}<br>
        Answered by {{ answer.answered_by }} at {{ answer.published_date }}
        <a class="small deletelink" href="{% url 'question:answer_delete' question.slug answer.pk%}">Delete</a>
        <hr class="form-horizontal">
        {% for comment in answer.comment_set.all %}
            {{ comment.body | linebreaks | markdown }} - {{ comment.user_name }} at {{ comment.pub_date }}&nbsp;
            <a class="small" href="{% url 'question:delete_comment' comment.pk question.slug %}">Delete</a>
            <hr class="form-horizontal">
        {% endfor %}
        <a style="color: #5e5e5e" href="{% url 'question:comment' question.slug answer.pk 'answer' %}">Add a Comment</a>
    <br><hr>
    {% endfor %}

    <div style="text-align: center;"><a href="{% url 'question:answer' slug=question.slug %}">
        <button class="btn btn-primary" type="submit">Answer this question</button>
    </a></div>
{% endblock %}