website/blog/urls.py
# coding=utf-8
from django.conf.urls import url
from .views import *


urlpatterns = [
    url(r'^$', index, name='index'),
]

website/users/urls.py
# coding=utf-8
from django.conf.urls import url
from .views import UserLoginView, logout_user, UserDetailView, UserRegisterView

urlpatterns = [
    url(r'^login/$', UserLoginView.as_view(), name='login_user'),
    url(r'^logout/$', logout_user, name='logout_user'),
    url(r'^register/$', UserRegisterView.as_view(), name='register_user'),
    url(r'^(?P<username>[-\w]+)/$', UserDetailView.as_view(), name='user_details'),
]

website/website/urls.py
# coding=utf-8
"""
website URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^u/', include('users.urls', namespace='users', app_name='users')),
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
    url(r'^', include('Questionnaire.urls', namespace="question", app_name="question")),
]
if settings.DEBUG:
    from django.contrib import admin
    import debug_toolbar
    urlpatterns.insert(0, url(r'^admin/', admin.site.urls))
    urlpatterns.insert(0, url(r'^debug/', include(debug_toolbar.urls)))

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/Questionnaire/models.py
# coding=utf-8
from .helpers import generate_random_id
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse
from django.utils import timezone

class Question(models.Model):
    title = models.CharField(max_length=250)
    body = models.TextField()
    asked_by = models.ForeignKey("users.UserModel")
    pub_date = models.DateTimeField(auto_now_add=timezone.now)
    slug = models.SlugField(max_length=350, unique=True)
    up_votes = models.PositiveIntegerField(default=0)
    down_votes = models.PositiveIntegerField(default=0)

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        # super(Question, self).save(force_insert, force_update, using, update_fields)
        if not self.slug:
            self.slug = slugify(self.title)+"-"+generate_random_id()
        super(Question, self).save(force_insert, force_update, using, update_fields)

    def get_absolute_url(self):
        return reverse('question:details', kwargs={'slug': self.slug})

    def __str__(self):
        return self.title


class Answer(models.Model):
    answer = models.TextField()
    question = models.ForeignKey(Question, models.CASCADE)
    published_date = models.DateTimeField(auto_now_add=timezone.now)
    last_edited = models.DateTimeField(auto_now=timezone.now)
    answered_by = models.ForeignKey('users.UserModel', models.CASCADE)
    draft = models.BooleanField(default=False)
    up_votes = models.PositiveIntegerField(default=0)
    down_votes = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.question.title+"===>"+self.answer[:31]


class Comment(models.Model):
    question_relation = models.ForeignKey(Question, models.CASCADE, blank=True, null=True)
    answer_relation = models.ForeignKey(Answer, models.CASCADE, blank=True, null=True)
    body = models.CharField(max_length=300)
    pub_date = models.DateTimeField(auto_now_add=True)
    comment_by = models.ForeignKey('users.UserModel', models.CASCADE)
    up_votes = models.PositiveIntegerField(default=0)
    down_votes = models.PositiveIntegerField(default=0)

    def __str__(self):
        return "{0} by {1} at {2}".format(self.body, self.comment_by, self.pub_date)

website/users/models.py
# coding=utf-8
from django.conf import settings
from django.db import models
from django.contrib.auth.models import AbstractUser, UserManager


class UserModel(AbstractUser):
    # User's details
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField(unique=True, blank=True)
    user_details = models.TextField(max_length=200)
    profile_pictures = models.ImageField(blank=True)

    # House Keeping details
    date_joined = models.DateTimeField(auto_now_add=True)
    is_staff = models.BooleanField(default=False, editable=False)
    is_superuser = models.BooleanField(default=False, editable=False)

    objects = UserManager()

    REQUIRED_FIELDS = ['email', 'first_name', 'last_name']

    class Meta:
        verbose_name = 'Registered User'
        verbose_name_plural = 'Registered Users'

    def get_short_name(self):
        "Returns the short name for the user."
        return self.username

    def get_full_name(self):
        return "%s %s" %(self.first_name, self.last_name)

website/users/forms.py
# coding=utf-8
from django import forms
from django.contrib.auth import get_user_model, login
from .models import UserModel


class UserLoginForm(forms.Form):
    username = forms.CharField()
    # email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput())


class UserRegisterForm(forms.ModelForm):
    username = forms.CharField(
        max_length=150,
        label="Enter a username for you account within 150 letters"
    )

    password = forms.CharField(widget=forms.PasswordInput(), label="Create a password")
    password2 = forms.CharField(widget=forms.PasswordInput(), label="Confirm your password")

    email = forms.EmailField(label="Enter a valid e-mail id (optional)", required=False)

    def is_valid(self):
        if self.password != self.password2:
            return False
        return super(UserRegisterForm, self).is_valid()

    class Meta:
        model = UserModel
        fields = ['username', 'first_name', 'last_name', 'email', 'password']

website/users/views.py
# coding=utf-8
from django.shortcuts import Http404
from django.shortcuts import redirect, render_to_response
from django.contrib.auth import login, logout, decorators, authenticate
from django.views.generic import FormView, DetailView, CreateView
from .forms import UserLoginForm, UserRegisterForm
from .models import UserModel


class UserLoginView(FormView):
    template_name = 'users/login.html'
    model = UserModel
    form_class = UserLoginForm


    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            user_name = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=user_name, password=password)
            if user:
                login(request, user)
                return redirect('users:user_details', username=user_name)
            else:
                return self.get(request)

@decorators.login_required
def logout_user(request):
        logout(request)
        return redirect('question:index')


class UserDetailView(DetailView):
    model = UserModel
    template_name = 'users/user_details.html'
    context_object_name = 'user'
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRegisterView(CreateView):
    model = UserModel
    form_class = UserRegisterForm
    template_name = 'users/user_register.html'

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        print(form.is_valid())
        if form.is_valid():
            user_model = form.save(commit=False)
            print(user_model)
            user_model.password = user_model.set_password(user_model.password)
            user_model.save()
            user_model = authenticate(username=user_model.username, password=user_model.password)
            print(user_model)
            login(request, user=user_model)
            return redirect('users:user_details', username=user_model.username)
        else:
            return Http404(message="The credentials were not valid")

website/templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}
    {% endblock %}</title>

    {% load staticfiles %}
    <!-- Load the jQuery library -->
    <script src="{% static 'Questionnaire/js/vendor/jquery.js' %}"></script>

    <!-- Load the bootstrap file's -->
    <!-- <link rel="stylesheet" href="{% static 'Questionnaire/bootstrap.min.css' %}"> -->
    <link rel="stylesheet" href="{% static 'Questionnaire/flatly.min.css' %}">
    <script src="{% static 'Questionnaire/bootstrap.min.js' %}"></script>

    <!-- Load the app specific stuff -->
    <link rel="stylesheet" href="{% static 'Questionnaire/app.css' %}">
    <script src="{% static 'Questionnaire/app.js' %}"></script>

    <!-- The Google fonts links -->
    <link href="https://fonts.googleapis.com/css?family=Lemonada" rel="stylesheet">

</head>
<body>
    <!-- Start Top Bar -->
    <nav class="navbar navbar-default">
        <div class="container-fluid">
        <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <div class="navbar-brand lemonada">Questionn</div>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
            <ul class="dropdown-menu dropdown-menu-right" role="menu">
                <li><a href="{% url 'question:index' %}">Visit Questionn</a></li>
                <li><a href="{% url 'blog:index' %}">Visit Blogg</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li><a href="#">Separated link</a></li>
                <li class="divider"></li>
                <li><a href="{% url 'users:logout_user' %}">Logout</a></li>
            </ul>
        </li>
    </ul>
    <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
            <input class="form-control" placeholder="Search" type="text">
        </div>
        <button type="submit" class="btn btn-success">Submit</button>
    </form>
    </div>
    </div>
    </nav>
    <!-- End Top Bar -->
    {% block body %}{% endblock %}

    <script>
      $(document).foundation();
    </script>
</body>
</html>

website/templates/users/login.html
{% extends 'users/base.html' %}

{% block title %}
    Login | Questionn
{% endblock %}

{% block body %}
    {% load crispy_forms_tags %}
    <form method="post" action="{% url 'users:login_user' %}" enctype="multipart/form-data">
    <button class="btn btn-primary" type="submit" value="submit">Login</button>
    {% crispy form %}
    </form>
{% endblock %}

website/templates/users/user_details.html
{% extends 'users/base.html' %}

{% block title %}
    {{ user.username }} | Questionn
{% endblock %}

{% block body %}
    <div class="center-block text-center">{{ user.get_full_name }}</div>

    <ul>
    {% for question in user.question_set.all %}
        <li>{{ question.title }}</li>
    {% endfor %}
    </ul>

{% endblock %}

website/templates/users/user_register.html
{% extends 'users/base.html' %}

{% block title %}
    Register | Questionn
{% endblock %}

{% block body %}
    {% load crispy_forms_tags %}
    <form method="post" action="{% url 'users:register_user' %}" enctype="multipart/form-data">
    <button class="btn btn-primary btn-success" type="submit" value="submit">Register</button>
    {% csrf_token %}
    {% crispy form %}
    </form>
{% endblock %}